spring:
  datasource:
    url: jdbc:mysql://localhost:3306/facebook
    username: test
    password: 12345
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
#  h2:
#    console:
#      path: /h2-console
#      settings:
#        trace: false
#        web-allow-others: false
  jackson:
    default-property-inclusion: NON_NULL
  security:
    oauth2:
      client:
        registration:
          facebook:
            client_id: 1173065959810832
            client_secret: 1b5c367758a336c162898f994e838c60
            scope:
              - email
              - public_profile